Repository boostcamp-2020/Project06-A-Slack, pull requests merged in 2020-12, with the labels that each got.

#46 채널을 생성하는 모달을 서버 패칭까지 완료, 유저 정보를 보는 모달을 구현
  client/package-lock.json
  client/src/components/ChannelListBox/ChannelList/Channel/ChannelItem.tsx
  client/src/components/ChannelListBox/ChannelList/ChannelList.tsx
  client/src/components/ChannelListBox/ChannelListHeader/ChannelListHeader.tsx
  client/src/components/ChannelModal/AddUserModal.tsx
  client/src/components/ChannelModal/CreateChannelModal.tsx
  client/src/components/ChannelModal/ShowUsersModal.tsx
  client/src/components/DetailBox/DetailList/DetailList.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ThreadListHeader.tsx
  client/src/components/index.ts
  client/src/hooks/index.ts
  client/src/hooks/useChannel.ts
  client/src/hooks/useOnClickOutside.ts
  client/src/pages/HomePage.tsx
  client/src/services/channel.service.ts
  client/src/services/index.ts
  client/src/store/modules/channel.ts
  client/src/store/sagas/channelSaga.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/src/types/channel.ts
  client/src/types/channelInfo.ts
  client/src/types/index.ts
  client/src/types/joinUser.ts
  client/src/utils/utils.ts
  server/src/models/channels.ts
  server/src/models/thread.ts
  server/src/routes/api/channels/[channelId]/channelId.controller.ts
  server/src/routes/api/channels/channels.controller.ts
  server/src/routes/api/channels/index.ts
  server/src/routes/api/users/[userId]/index.ts
  server/src/routes/api/users/[userId]/userId.controller.ts
Labels: api, backend, frontend

#49 App에서 WorkSpacePage 분리
  client/src/App.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/WorkSpacePage.tsx
  client/src/pages/index.ts
Labels: frontend

#50 RightSideBar 추가
  client/src/components/common/RightSideBar/RightSideBar.tsx
  client/src/components/common/index.ts
Labels: feat, frontend

#54 모달이나 채널리스트의 상태는 지역에서 관리로 수정, 왼쪽 사이드 바에 dm을 추가, 쓰레드 리스트 헤더 구현
  client/src/components/ChannelListBox/ChannelList/ChannelList.tsx
  client/src/components/ChannelListBox/ChannelListBox.tsx
  client/src/components/ChannelListBox/ChannelListHeader/ChannelListHeader.tsx
  client/src/components/ChannelModal/AddTopicModal.tsx
  client/src/components/ChannelModal/AddUsersModal.tsx
  client/src/components/ChannelModal/CreateChannelModal.tsx
  client/src/components/ChannelModal/ShowUsersModal.tsx
  client/src/components/DetailBox/DeatailHeader/DetailHeader.tsx
  client/src/components/DetailBox/DetailBody/DetailBody.tsx
  client/src/components/DetailBox/DetailBody/DetailButtonBox/DetailButtonBox.tsx
  client/src/components/DetailBox/DetailBody/DetailList/DetailList.tsx
  client/src/components/DetailBox/DetailBox.tsx
  client/src/components/LeftSideBar/LeftSideBarContent/LeftSideBarContent.tsx
  client/src/components/LeftSideBar/LeftSideBarHeader/LeftSideBarHeader.tsx
  client/src/components/LeftSideBar/LeftSidebar.tsx
  client/src/components/ThreadListBox/ThreadListBox.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ThreadListHeader.tsx
  client/src/components/common/RightSideBar/RightSideBar.tsx
  client/src/components/index.ts
  client/src/pages/WorkSpacePage.tsx
  client/src/store/modules/channel.ts
  client/src/utils/constants.ts
Labels: frontend, 왼쪽 사이드바 - 채널

#53 공통 dim modal 구현, menu 전용 modal 구현
  client/package-lock.json
  client/package.json
  client/src/components/EmailBox/EmailBox.tsx
  client/src/components/ThreadListBox/ThreadList/ThreadList.tsx
  client/src/components/common/DimModal/DimModal.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Header/UserProfileModalBox/UserProfileBody/UserProfileBody.tsx
  client/src/components/common/Header/UserProfileModalBox/UserProfileFooter/UserProfileFooter.tsx
  client/src/components/common/Header/UserProfileModalBox/UserProfileHeader/UserProfileHeader.tsx
  client/src/components/common/Header/UserProfileModalBox/index.ts
  client/src/components/common/MenuModal/MenuModal.tsx
  client/src/components/common/ModalCloseBox/ModalCloseBox.tsx
  client/src/components/common/UserStateIcon/UserStateIcon.tsx
  client/src/components/common/index.ts
  client/src/hooks/index.ts
  client/src/hooks/useOnClickOutside.ts
  client/src/styles/mixin.ts
  client/src/styles/shared/button.ts
  client/src/styles/shared/index.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
Labels: frontend, 헤더

#56 RightSideBar 부분 구현 / uilts 함수 작성 / thread, subthread 쿼리 수정 / 라우팅적용 / 리펙토링
  client/src/App.tsx
  client/src/components/ChannelListBox/ChannelList/Channel/ChannelItem.tsx
  client/src/components/SubThreadListBox/ParentThread/ParentThread.tsx
  client/src/components/SubThreadListBox/ReplyCountHorizon/ReplyCountHorizon.tsx
  client/src/components/SubThreadListBox/SubThreadList/SubThreadList.tsx
  client/src/components/SubThreadListBox/SubThreadListBox.tsx
  client/src/components/ThreadListBox/ThreadInputBox/ThreadInputBox.tsx
  client/src/components/ThreadListBox/ThreadList/ThreadList.tsx
  client/src/components/ThreadListBox/ThreadListBox.tsx
  client/src/components/common/RightSideBar/RightSideBar.tsx
  client/src/components/common/RightSideBar/RightSideBarBody/RightSideBarBody.tsx
  client/src/components/common/RightSideBar/RightSideBarHeader/RightSideBarHeader.tsx
  client/src/components/common/ThreadItem/ReplyButton/ReplyButton.tsx
  client/src/components/common/ThreadItem/ThreadItem.tsx
  client/src/components/common/ThreadItem/ThreadPopup/ThreadPopup.tsx
  client/src/hooks/index.ts
  client/src/pages/HomePage.tsx
  client/src/pages/WorkSpacePage.tsx
  client/src/services/subThread.service.ts
  client/src/store/modules/subThread.ts
  client/src/store/modules/thread.ts
  client/src/store/sagas/channelSaga.ts
  client/src/store/sagas/subThreadSaga.ts
  client/src/types/joinUser.ts
  client/src/types/thread.ts
  client/src/utils/constants.ts
  client/src/utils/utils.ts
  server/src/models/thread.ts
  server/src/routes/api/threads/[threadId]/threadId.controller.ts
  server/src/routes/api/threads/threads.controller.ts
Labels: api, backend, feat, frontend, refactor

#58 라우팅 예외처리 / 쓰레드 생성 api, 사가로직 구현
  client/src/components/SubThreadListBox/SubThreadListBox.tsx
  client/src/components/ThreadListBox/ThreadInputBox/ThreadInputBox.tsx
  client/src/components/ThreadListBox/ThreadListBox.tsx
  client/src/components/common/ThreadInputBox/ThreadInputBox.tsx
  client/src/components/common/ThreadItem/ThreadItem.tsx
  client/src/components/common/ThreadItem/ThreadPopup/ThreadPopup.tsx
  client/src/components/common/index.ts
  client/src/pages/WorkSpacePage.tsx
  client/src/services/thread.service.ts
  client/src/store/modules/thread.ts
  client/src/store/sagas/threadSaga.ts
  client/src/types/thread.ts
  client/src/utils/constants.ts
  server/src/models/thread.ts
  server/src/routes/api/threads/[threadId]/threadId.controller.ts
  server/src/routes/api/threads/threads.controller.ts
Labels: api, backend, feat, frontend, refactor

#59 유저 프로필 수정 / 사진 업로드 / 사진 제거 / 기본 이미지 적용
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/common/DimModal/DimModal.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Header/UserProfileBox/UserProfileBody/UserProfileBody.tsx
  client/src/components/common/Header/UserProfileBox/UserProfileHeader/UserProfileHeader.tsx
  client/src/components/common/Header/UserProfileBox/index.ts
  client/src/components/common/Header/UserProfileModalBox/UserProfileBody/UserProfileBody.tsx
  client/src/components/common/Header/UserProfileModalBox/UserProfileFooter/UserProfileFooter.tsx
  client/src/components/common/MenuModal/MenuModal.tsx
  client/src/index.tsx
  client/src/services/user.service.ts
  client/src/store/modules/user.ts
  client/src/store/sagas/userSaga.ts
  client/src/styles/shared/button.ts
  client/src/styles/shared/form.ts
  client/src/types/user.ts
  client/src/utils/constants.ts
  server/src/app.ts
  server/src/models/user.ts
  server/src/routes/api/auth/auth.controller.ts
  server/src/routes/api/users/[userId]/index.ts
  server/src/routes/api/users/[userId]/userId.controller.ts
  server/src/routes/api/users/[userId]/userId.yaml
  server/src/utils/constants.ts
Labels: api, backend, frontend, 헤더

#60 페이징 라우팅 구현, joinChannelList에서 myChannelList로 상태명 변경
  client/src/components/ChannelListBox/ChannelList/ChannelItem/ChannelItem.tsx
  client/src/components/ChannelListBox/ChannelList/ChannelList.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ThreadListHeader.tsx
  client/src/hooks/useChannel.ts
  client/src/pages/WorkSpacePage.tsx
  client/src/services/channel.service.ts
  client/src/store/modules/channel.ts
  client/src/store/sagas/channelSaga.ts
  client/src/types/user.ts
  client/src/utils/utils.ts
  server/src/models/user.ts
  server/src/routes/api/users/[userId]/userId.controller.ts
Labels: frontend

#61 MenuModal 수정사항 반영, 소켓 관련 saga, reducer 기본 구현
  client/src/App.tsx
  client/src/components/common/MenuModal/MenuModal.tsx
  client/src/components/common/ThreadItem/ThreadPopup/ThreadPopup.tsx
  client/src/hooks/index.ts
  client/src/hooks/useSocketState.ts
  client/src/store/modules/index.ts
  client/src/store/modules/socket.ts
  client/src/store/sagas/index.ts
  client/src/store/sagas/socketSaga.ts
  client/src/utils/constants.ts
  server/src/app.ts
  server/src/lib/socket.ts
  server/src/utils/constants.ts
Labels: backend

#64 쓰레드 생성시 subThread 정보 업데이트 관련 코드 작성 / 리펙토링
  client/src/components/ThreadListBox/ThreadList/ThreadList.tsx
  client/src/components/common/ThreadItem/ThreadPopup/ThreadPopup.tsx
  server/src/models/thread.ts
  server/src/routes/api/threads/[threadId]/threadId.controller.ts
  server/src/routes/api/threads/threads.controller.ts
Labels: api, backend, feat, refactor

#65 리팩토링
  client/src/App.tsx
  client/src/hoc/RestrictRoute.tsx
  client/src/hoc/index.ts
  client/src/services/auth.service.ts
  client/src/services/channel.service.ts
  client/src/services/subThread.service.ts
  client/src/services/thread.service.ts
  client/src/services/user.service.ts
  client/src/types/index.ts
  client/src/types/service.ts
Labels: refactor

#68 smtp 설정 추가
  server/package-lock.json
  server/package.json
  server/src/utils/utils.ts
Labels: backend, bug-fix

#70 유저 정보만 변경 시 이미지 삭제하는 오류 수정
  client/src/store/sagas/userSaga.ts
  server/src/routes/api/users/[userId]/userId.controller.ts
Labels: api, backend, frontend

#74 hooks 네이밍 변경과 일부 불필요한 import 구문 짧게 변경
  client/src/components/ChannelListBox/ChannelList/ChannelItem/ChannelItem.tsx
  client/src/components/ChannelListBox/ChannelList/ChannelList.tsx
  client/src/components/ChannelListBox/ChannelListHeader/CreateChannelModal/CreateChannelModalBody/CreateChannelModalBody.tsx
  client/src/components/DetailBox/DeatailHeader/DetailHeader.tsx
  client/src/components/DetailBox/DetailBody/DetailList/DetailList.tsx
  client/src/components/LeftSideBar/LeftSidebar.tsx
  client/src/components/SubThreadListBox/SubThreadListBox.tsx
  client/src/components/ThreadListBox/ThreadList/ThreadList.tsx
  client/src/components/ThreadListBox/ThreadListBox.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/AddTopicModal/AddTopicModalBody/AddTopicModalBody.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/AddUsersModal/AddUsersModalBody/addUsersModalBody.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/AddUsersModal/AddUsersModalHeader/addUsersModalHeader.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/ShowUsersModal/ShowUsersModalBody/ShowUsersModalBody.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/ShowUsersModal/ShowUsersModalHeader/ShowUsersModalHeader.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ThreadListHeader.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Header/UserProfileBox/UserProfileBody/UserProfileBody.tsx
  client/src/components/common/ThreadInputBox/ThreadInputBox.tsx
  client/src/components/common/ThreadItem/ReplyButton/ReplyButton.tsx
  client/src/components/common/ThreadItem/ThreadItem.tsx
  client/src/hooks/index.ts
  client/src/hooks/useAuthState.ts
  client/src/hooks/useChannelState.ts
  client/src/hooks/useSubThreadState.ts
  client/src/hooks/useThreadState.ts
  client/src/hooks/useUserState.ts
  client/src/pages/HomePage.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/WorkSpacePage.tsx
Labels: refactor

#79 reply에 프로필 이미지 뜨도록 적용 / 메인 쓰레드에서 입력시 예외처리 버그 수정
  client/src/components/common/ThreadItem/ReplyButton/ReplyButton.tsx
  server/src/routes/api/threads/threads.controller.ts
Labels: api, backend, bug-fix, feat, frontend

#78 리펙토링, 채널에 유저 추가
  client/src/components/DetailBox/DetailBody/DetailList/DetailList.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/AddTopicModal/AddTopicModalBody/AddTopicModalBody.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/AddUsersModal/AddUsersModalBody/addUsersModalBody.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/ShowUsersModal/ShowUsersModalBody/ShowUsersModalBody.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ThreadListHeader.tsx
  client/src/services/channel.service.ts
  client/src/services/user.service.ts
  client/src/store/modules/channel.slice.ts
  client/src/store/modules/user.slice.ts
  client/src/store/sagas/channelSaga.ts
  client/src/store/sagas/userSaga.ts
  server/src/models/channels.model.ts
  server/src/models/user.model.ts
  server/src/routes/api/channels/[channelId]/channelId.controller.ts
  server/src/routes/api/users/index.ts
  server/src/routes/api/users/users.controller.ts
  server/src/types/index.ts
Labels: api, backend, frontend, refactor

#75 디자인 적용, 소켓 로직 정의 및 구현
  client/src/components/ChannelListBox/ChannelList/ChannelItem/ChannelItem.tsx
  client/src/components/ChannelListBox/ChannelListHeader/ChannelListHeader.tsx
  client/src/components/ChannelListBox/ChannelListHeader/CreateChannelModal/CreateChannelModalBody/CreateChannelModalBody.tsx
  client/src/components/DetailBox/DetailBody/DetailList/DetailList.tsx
  client/src/components/LeftSideBar/LeftSideBarContent/LeftSideBarContent.tsx
  client/src/components/LeftSideBar/LeftSideBarHeader/LeftSideBarHeader.tsx
  client/src/components/LeftSideBar/LeftSidebar.tsx
  client/src/components/ThreadListBox/ThreadList/ThreadList.tsx
  client/src/components/ThreadListBox/ThreadListBox.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/ShowUsersModal/ShowUsersModalBody/ShowUsersModalBody.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ThreadListHeader.tsx
  client/src/components/common/DimModal/DimModal.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Icon/AddUserIcon/AddUserIcon.tsx
  client/src/components/common/Icon/ArrowDownIcon/ArrowDownIcon.tsx
  client/src/components/common/Icon/ArrowRightIcon/ArrowRightIcon.tsx
  client/src/components/common/Icon/ClockIcon/ClockIcon.tsx
  client/src/components/common/Icon/CommentIcon/CommentIcon.tsx
  client/src/components/common/Icon/DotIcon/DotIcon.tsx
  client/src/components/common/Icon/LockIcon/LockIcon.tsx
  client/src/components/common/Icon/PaperPlaneIcon/PaperPlaneIcon.tsx
  client/src/components/common/Icon/PlusIcon/PlusIcon.tsx
  client/src/components/common/Icon/PoundIcon/PoundIcon.tsx
  client/src/components/common/Icon/ReactionIcon/ReactionIcon.tsx
  client/src/components/common/Icon/RightIcon/RightIcon.tsx
  client/src/components/common/Icon/UserStateIcon/UserStateIcon.tsx
  client/src/components/common/Icon/WarningIcon/WarningIcon.tsx
  client/src/components/common/Icon/WriteIcon/WriteIcon.tsx
  client/src/components/common/Icon/index.ts
  client/src/components/common/MenuModal/MenuModal.tsx
  client/src/components/common/ThreadInputBox/ThreadInputBox.tsx
  client/src/components/common/ThreadItem/ReplyButton/ReplyButton.tsx
  client/src/components/common/ThreadItem/ThreadItem.tsx
  client/src/components/common/ThreadItem/ThreadPopup/ThreadPopup.tsx
  client/src/components/common/WarningIcon/WarningIcon.tsx
  client/src/components/common/index.ts
  client/src/pages/WorkSpacePage.tsx
  client/src/store/modules/channel.slice.ts
  client/src/store/modules/socket.slice.ts
  client/src/store/modules/thread.slice.ts
  client/src/store/sagas/channelSaga.ts
  client/src/store/sagas/socketSaga.ts
  client/src/styles/mixin.ts
  client/src/styles/styled.d.ts
  client/src/styles/theme.ts
  client/src/types/index.ts
  client/src/types/joinedUser.ts
  client/src/types/thread.ts
  client/src/utils/utils.ts
  server/src/lib/socket.ts
  server/src/routes/api/users/[userId]/userId.controller.ts
Labels: frontend

#83 emoji 관련 백엔드 api 구현 / 쓰레드 목록에 이모지 뿌려주는것 구현
  client/src/components/common/ThreadItem/EmojiBox/EmojiBox.tsx
  client/src/components/common/ThreadItem/EmojiBox/EmojiBoxItem/EmojiBoxItem.tsx
  client/src/components/common/ThreadItem/ThreadItem.tsx
  client/src/types/thread.ts
  server/src/models/emoji.model.ts
  server/src/models/index.ts
  server/src/routes/api/emojis/emojis.controllers.ts
  server/src/routes/api/emojis/index.ts
  server/src/routes/api/index.ts
Labels: api, backend, feat, frontend

#84 소켓 이벤트 컨벤션, 타입, 상수 정의, 채팅 구현
  client/package.json
  client/src/api/index.ts
  client/src/components/ThreadListBox/ThreadList/ThreadList.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ThreadListHeader.tsx
  client/src/components/common/ThreadInputBox/ThreadInputBox.tsx
  client/src/store/modules/socket.slice.ts
  client/src/store/modules/thread.slice.ts
  client/src/store/sagas/channelSaga.ts
  client/src/store/sagas/socketSaga.ts
  client/src/store/sagas/threadSaga.ts
  client/src/types/index.ts
  client/src/types/socket.ts
  client/src/utils/constants.ts
  server/src/lib/socket.ts
  server/src/models/thread.model.ts
  server/src/routes/api/channels/[channelId]/channelId.controller.ts
  server/src/routes/api/channels/channels.controller.ts
  server/src/routes/api/threads/[threadId]/threadId.controller.ts
  server/src/routes/api/threads/threads.controller.ts
  server/src/routes/api/users/[userId]/userId.controller.ts
  server/src/services/index.ts
  server/src/services/thread.service.ts
  server/src/utils/constants.ts
Labels: api, backend, bug-fix, frontend, refactor, 소켓, 컨벤션

#91 채널 소켓 작업
  client/src/components/ChannelListBox/ChannelList/ChannelList.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/AddTopicModal/AddTopicModalBody/AddTopicModalBody.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/AddUsersModal/AddUsersModalBody/addUsersModalBody.tsx
  client/src/store/modules/channel.slice.ts
  client/src/store/sagas/channelSaga.ts
  client/src/store/sagas/socketSaga.ts
  client/src/types/channel.ts
  client/src/types/socket.ts
  server/src/lib/socket.ts
Labels: backend, frontend, 소켓, 수정사항, 왼쪽 사이드바 - 채널

#95 Popover 커스텀 완료
  client/src/components/ChannelListBox/ChannelListBox.tsx
  client/src/components/ChannelListBox/ChannelListHeader/ChannelListHeader.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Popover/Popover.tsx
  client/src/components/common/ThreadItem/ThreadItem.tsx
  client/src/components/common/ThreadItem/ThreadPopup/ThreadPopup.tsx
  client/src/components/common/index.ts
Labels: frontend, refactor

#94 dm방 만드는 것을 소켓으로 구현
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/AddUsersModal/AddUsersModalBody/AddUsersModalBody.tsx
  client/src/store/sagas/socketSaga.ts
  client/src/types/socket.ts
  client/src/utils/constants.ts
  server/src/lib/socket.ts
  server/src/models/channels.model.ts
  server/src/utils/constants.ts
Labels: backend, frontend, 소켓, 왼쪽 사이드바 - 채널

#96 reaction box 에 새로운 Popover 적용 및 window 밖으로 커서 나갔을 때 처리
  client/src/components/common/ThreadItem/ThreadItem.tsx
  client/src/components/common/ThreadItem/ThreadPopup/ThreadPopup.tsx
Labels: frontend

#100 실시간 이모지 subThread에서도 동작되도록 수정 / 불필요한 코드 제거 (popover)
  client/src/components/common/EmojiListModal/EmojiListModal.tsx
  client/src/components/common/Popover/Popover.tsx
  client/src/components/common/ThreadItem/EmojiBox/EmojiBoxItem/EmojiBoxItem.tsx
  client/src/store/modules/subThread.slice.ts
  client/src/store/modules/thread.slice.ts
  client/src/store/sagas/socketSaga.ts
Labels: bug-fix, feat, frontend

#102 이모지 위치 댓글 위로 변경
  client/src/components/common/ThreadItem/ThreadItem.tsx
Labels: hot-fix

#106 우측 사이드바 공통 컴포넌트 구현 및 디테일/서브스레드 주입
  client/src/App.tsx
  client/src/api/index.ts
  client/src/components/ChannelListBox/ChannelListHeader/CreateChannelModal/CreateChannelModalBody/CreateChannelModalBody.tsx
  client/src/components/DetailBox/DeatailHeader/DetailHeader.tsx
  client/src/components/DetailBox/DetailBody/DetailButtonBox/DetailButtonBox.tsx
  client/src/components/DetailBox/DetailBody/DetailList/DetailList.tsx
  client/src/components/SubThreadListBox/SubThreadListBox.tsx
  client/src/components/SubThreadListBox/SubThreadListHeader/SubThreadListHeader.tsx
  client/src/components/common/CloseIconBox/CloseIconBox.tsx
  client/src/components/common/Icon/RightArrowLineIcon/RightArrowLineIcon.tsx
  client/src/components/common/Icon/index.ts
  client/src/components/common/RightSideBar/RightSideBar.tsx
  client/src/components/common/RightSideBar/RightSideBarBody/RightSideBarBody.tsx
  client/src/components/common/RightSideBar/RightSideBarHeader/RightSideBarHeader.tsx
  client/src/components/common/ThreadItem/EmojiBox/EmojiBox.tsx
  client/src/components/common/ThreadItem/EmojiBox/EmojiBoxItem/EmojiBoxItem.tsx
  client/src/components/common/ThreadItem/ReplyButton/ReplyButton.tsx
  client/src/components/common/index.ts
  client/src/components/index.ts
  client/src/hoc/index.ts
  client/src/hoc/withAuth.tsx
  client/src/hooks/index.ts
  client/src/hooks/useRedirectState.ts
  client/src/pages/HomePage.tsx
  client/src/pages/WorkSpacePage.tsx
  client/src/store/modules/channel.slice.ts
  client/src/store/modules/index.ts
  client/src/store/modules/redirect.slice.ts
  client/src/store/sagas/channelSaga.ts
Labels: frontend

#108 회원가입, 이메일 중복 검증, loading 아이콘 구현 및 에러 수정
  client/src/api/index.ts
  client/src/components/CodeVerifyBox/CodeVerifyBox.tsx
  client/src/components/EmailBox/EmailBox.tsx
  client/src/components/SignupBox/SignupBox.tsx
  client/src/components/SubThreadListBox/SubThreadListHeader/SubThreadListHeader.tsx
  client/src/components/common/Header/UserProfileBox/UserProfileBody/UserProfileBody.tsx
  client/src/components/index.ts
  client/src/pages/SignupPage.tsx
  client/src/public/icon/loading.svg
  client/src/services/auth.service.ts
  client/src/store/modules/signup.slice.ts
  client/src/store/modules/user.slice.ts
  client/src/store/sagas/channelSaga.ts
  client/src/store/sagas/signupSaga.ts
  client/src/types/asset.d.ts
  client/tsconfig.json
  server/src/models/user.model.ts
  server/src/routes/api/auth/auth.controller.ts
  server/src/routes/api/auth/index.ts
  server/src/utils/constants.ts
Labels: api, backend, frontend, 회원가입

#110 채널 사가/reducer 타입 명시 및 오류 수정, 인피니티 스크롤 구현, 디자인 작업 등
  client/package-lock.json
  client/package.json
  client/src/components/ChannelListBox/ChannelList/ChannelList.tsx
  client/src/components/ChannelListBox/ChannelListHeader/ChannelListHeader.tsx
  client/src/components/ChannelListBox/ChannelListHeader/CreateChannelModal/CreateChannelModalBody/CreateChannelModalBody.tsx
  client/src/components/ChannelListBox/ChannelListHeader/CreateChannelModal/CreateChannelModalHeader/CreateChannelModalHeader.tsx
  client/src/components/CodeVerifyBox/CodeVerifyBox.tsx
  client/src/components/DetailBox/DetailBody/DetailList/DetailList.tsx
  client/src/components/SubThreadListBox/SubThreadListHeader/SubThreadListHeader.tsx
  client/src/components/ThreadListBox/ThreadList/ThreadList.tsx
  client/src/components/ThreadListBox/ThreadListBox.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/AddTopicModal/AddTopicModalBody/AddTopicModalBody.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/AddTopicModal/AddTopicModalHeader/AddTopicModalHeader.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/AddUsersModal/AddUsersModalBody/AddUsersModalBody.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/AddUsersModal/AddUsersModalHeader/AddUsersModalHeader.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/ShowUsersModal/ShowUsersModalBody/ShowUsersModalBody.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ThreadListHeader.tsx
  client/src/components/common/AddUsersModal/AddUsersModalBody/AddUsersModalBody.tsx
  client/src/components/common/AddUsersModal/AddUsersModalHeader/AddUsersModalHeader.tsx
  client/src/components/common/AddUsersModal/index.ts
  client/src/components/common/DimModal/DimModal.tsx
  client/src/components/common/Header/UserProfileBox/UserProfileBody/UserProfileBody.tsx
  client/src/components/common/Header/UserProfileBox/UserProfileHeader/UserProfileHeader.tsx
  client/src/components/common/MenuModal/MenuModal.tsx
  client/src/components/common/Popover/Popover.tsx
  client/src/components/common/ThreadInputBox/ThreadInputBox.tsx
  client/src/components/common/ThreadItem/ThreadPopup/ThreadPopup.tsx
  client/src/components/common/index.ts
  client/src/hooks/index.ts
  client/src/hooks/useInfiniteScroll.ts
  client/src/public/icon/loading-color.svg
  client/src/services/thread.service.ts
  client/src/services/user.service.ts
  client/src/store/modules/channel.slice.ts
  client/src/store/modules/thread.slice.ts
  client/src/store/modules/user.slice.ts
  client/src/store/sagas/authSaga.ts
  client/src/store/sagas/channelSaga.ts
  client/src/store/sagas/socketSaga.ts
  client/src/store/sagas/threadSaga.ts
  client/src/store/sagas/userSaga.ts
  client/src/styles/mixin.ts
  server/package.json
  server/src/lib/redis.ts
  server/src/lib/socket.ts
  server/src/models/channels.model.ts
  server/src/models/emoji.model.ts
  server/src/models/thread.model.ts
  server/src/models/user.model.ts
  server/src/routes/api/auth/auth.controller.ts
  server/src/routes/api/channels/[channelId]/channelId.controller.ts
  server/src/routes/api/threads/threads.controller.ts
  server/src/routes/api/users/[userId]/userId.controller.ts
  server/src/routes/api/users/index.ts
  server/src/routes/api/users/users.controller.ts
  server/src/types/index.ts
  server/src/utils/constants.ts
Labels: api, backend, bug-fix, frontend, refactor

#119 delete 쓰레드 구현 / package-lock.json 안올라와있던것 추가
  client/package-lock.json
  client/src/components/SubThreadListBox/ParentThread/ParentThread.tsx
  client/src/components/SubThreadListBox/SubThreadList/SubThreadList.tsx
  client/src/components/ThreadListBox/ThreadList/ThreadList.tsx
  client/src/components/common/ThreadInputBox/ThreadInputBox.tsx
  client/src/components/common/ThreadItem/ThreadPopup/ThreadPopup.tsx
  client/src/store/modules/subThread.slice.ts
  client/src/store/modules/thread.slice.ts
  client/src/store/sagas/socketSaga.ts
  client/src/types/socket.ts
  client/src/types/thread.ts
  client/src/utils/constants.ts
  server/package-lock.json
  server/src/lib/socket.ts
  server/src/models/thread.model.ts
  server/src/services/thread.service.ts
  server/src/types/index.ts
  server/src/utils/constants.ts
Labels: api, backend, feat, frontend

#117 채널 검색 + 가입 구현, favicon 추가, 채널의 유저 리스트 디자인, unread 관련 버그 수정 등
  client/src/components/ChannelListBox/ChannelListHeader/ChannelListHeader.tsx
  client/src/components/ChannelListBox/ChannelListHeader/CreateChannelModal/CreateChannelModalBody/CreateChannelModalBody.tsx
  client/src/components/ChannelListBox/ChannelListHeader/FindChannelModal/FindChannelModalBody/FindChannelModalBody.tsx
  client/src/components/ChannelListBox/ChannelListHeader/FindChannelModal/FindChannelModalHeader/FindChannelModalHeader.tsx
  client/src/components/CodeVerifyBox/CodeVerifyBox.tsx
  client/src/components/EmailBox/EmailBox.tsx
  client/src/components/LoginBox/LoginBox.tsx
  client/src/components/SignupBox/SignupBox.tsx
  client/src/components/ThreadListBox/ThreadList/ThreadList.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/ShowUsersModal/ShowUsersModalBody/ShowUsersModalBody.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/ShowUsersModal/ShowUsersModalHeader/ShowUsersModalHeader.tsx
  client/src/components/ThreadListBox/ThreadListHeader/ThreadListHeader.tsx
  client/src/components/common/AddUsersModal/AddUsersModalBody/AddUsersModalBody.tsx
  client/src/components/common/Header/Header.tsx
  client/src/components/common/Header/UserProfileBox/UserProfileBody/UserProfileBody.tsx
  client/src/components/common/LogoBox/LogoBox.tsx
  client/src/components/common/ThreadInputBox/ThreadInputBox.tsx
  client/src/components/common/ThreadItem/ThreadItem.tsx
  client/src/components/common/index.ts
  client/src/hooks/index.ts
  client/src/hooks/useDuplicatedChannelState.ts
  client/src/pages/LoginPage.tsx
  client/src/pages/SignupPage.tsx
  client/src/public/icon/slack-logo.gif
  client/src/public/icon/slack-logo.svg
  client/src/public/icon/slack-logo.webp
  client/src/public/icon/slack.ico
  client/src/services/channel.service.ts
  client/src/store/modules/channel.slice.ts
  client/src/store/modules/duplicatedChannel.slice.ts
  client/src/store/modules/index.ts
  client/src/store/sagas/duplicatedChannelSaga.ts
  client/src/store/sagas/index.ts
  client/src/store/sagas/signupSaga.ts
  client/src/types/asset.d.ts
  client/src/utils/utils.ts
  client/webpack.config.js
  server/src/models/channels.model.ts
  server/src/routes/api/channels/[channelId]/channelId.controller.ts
  server/src/routes/api/channels/[channelId]/index.ts
  server/src/routes/api/channels/channels.controller.ts
  server/src/routes/api/channels/index.ts
Labels: backend, frontend, 세부 요구사항

#121 유저 프로필 변경 이벤트가 발생한 경우, 원래 정보에서 유저 프로필이 변경된 곳만 교체해주는 형식으로 코드 수정
  client/src/store/modules/channel.slice.ts
  client/src/store/modules/subThread.slice.ts
  client/src/store/modules/thread.slice.ts
  client/src/store/sagas/socketSaga.ts
Labels: frontend, 소켓

#120 로그아웃 시 불필요하게 남아있는 state 초기화
  client/src/components/EmailBox/EmailBox.tsx
  client/src/store/modules/channel.slice.ts
  client/src/store/modules/duplicatedChannel.slice.ts
  client/src/store/modules/signup.slice.ts
  client/src/store/modules/subThread.slice.ts
  client/src/store/modules/thread.slice.ts
  client/src/store/modules/user.slice.ts
  client/src/store/sagas/authSaga.ts
Labels: bug-fix, frontend

#122 로그인 loading 처리 / 실패시 안내 메시지 출력 + 스레드 edit/delete 버튼을 내가 쓴 댓글일때만 표시
  client/src/components/LoginBox/LoginBox.tsx
  client/src/components/SignupBox/SignupBox.tsx
  client/src/components/common/ThreadItem/ThreadPopup/ThreadPopup.tsx
  client/src/store/modules/auth.slice.ts
  client/src/store/sagas/authSaga.ts
Labels: 로그인, 세부 요구사항

#130 신규 가입 유저는 random 채널로 가도록구현
  server/src/lib/passport.ts
  server/src/lib/socket.ts
  server/src/models/channels.model.ts
  server/src/routes/api/auth/auth.controller.ts
  server/src/routes/api/oauth/oauth.controller.ts
Labels: api, backend

#132 [fix] 시크릿 모드에서 oauth 되게 구현변경
  client/src/components/LoginBox/LoginBox.tsx
  client/src/pages/LoginPage.tsx
  server/src/lib/passport.ts
  server/src/routes/api/oauth/oauth.controller.ts
Labels: bug-fix

#136 [fix] .env수정에 따른 코드 변경
  server/src/app.ts
  server/src/config/index.ts
  server/src/routes/api/oauth/oauth.controller.ts
Labels: bug-fix

#142 OAuth user image있으면 추가하도록 구현
  client/src/api/index.ts
  client/src/components/ThreadListBox/ThreadListHeader/ChannelModal/ShowUsersModal/ShowUsersModalBody/ShowUsersModalBody.tsx
  server/src/models/user.model.ts
  server/src/routes/api/oauth/oauth.controller.ts
Labels: backend

#146 인피니티 스크롤 버그 수정
  client/src/components/ThreadListBox/ThreadList/ThreadList.tsx
  client/src/components/common/ThreadInputBox/ThreadInputBox.tsx
  client/src/store/modules/thread.slice.ts
  client/src/store/sagas/socketSaga.ts
  client/src/store/sagas/threadSaga.ts
Labels: bug-fix

#150 같은 유저 연속된 스레드일 때 처리 / 채널 최상단에 도달했을 때 디자인 추가
  client/src/components/SubThreadListBox/ParentThread/ParentThread.tsx
  client/src/components/ThreadListBox/ThreadList/ThreadList.tsx
  client/src/components/common/Icon/ChannelLockIcon/ChannelLockIcon.tsx
  client/src/components/common/Icon/LightIcon/LightIcon.tsx
  client/src/components/common/Icon/TrashIcon/TrashIcon.tsx
  client/src/components/common/Icon/index.ts
  client/src/components/common/ThreadItem/EmojiBox/EmojiBox.tsx
  client/src/components/common/ThreadItem/ReplyButton/ReplyButton.tsx
  client/src/components/common/ThreadItem/ThreadItem.tsx
  client/src/components/common/ThreadItem/ThreadPopup/ThreadPopup.tsx
Labels: frontend

#159 map으로 isDeleted 필터하던것 filter로 변경
  client/src/components/SubThreadListBox/SubThreadList/SubThreadList.tsx
Labels: refactor
